target 'MyTrack' do

  # Pods for Google Maps SDk iOS
  pod 'GoogleMaps', '7.3.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyRealmProject
  pod 'RealmSwift', '~>10'
  
end